version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=golang_project

  api:
    build:
      context: .
      dockerfile:  Dockefile
    ports: 
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/golang_project?sslmode=disable
    depends_on:
      - postgres
    command: ["/app/main"]